### ISSUE TITLE
How do i use ClassGPT？What is the password in the http://localhost:8501/ ?

### ISSUE THREAD

**Issue by GH-charge-forward** [benthecoder/ClassGPT#1]
Hi, I am almost a stranger to these web tools. I followed your instructions and opened up the website http://localhost:8501/. There is a button on the top of the page "password". I tried my gmail passwords which are used to log into  and failed. 

What is this password for?

**Comment by benthecoder** [comment]
Yea sorry about that, thats for my deployed version.

If you do git pull again (assuming you cloned the repo), it shouldn't have password anymore.
