### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Hurwitzzz** [benthecoder/ClassGPT#2]
Hi, when I setup the environment, I found that the bucket name should be unique in global namespace and therefore I cannot create a bucket named classgpt.
I don't know if this is the reason for getting "Access Denied" (ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied) when I ran streamlit.

**Comment by benthecoder** [comment]
hi @Hurwitzzz create your own bucket, and change the lines in the code, it's in multiple files 

```py
bucket_name = "classgpt"
```

to 

```py
bucket_name = <YOUR_BUCKET_NAME>
```
